name: zRanks
version: 1.2
author: zPlugins
description: A simple permissions & chat management plugin
main: com.zp4rker.zranks.zRanks
database: true
commands:
    zranks:
        usage: §2/zranks <RELOAD>
        aliases: zr
        description: Reloads the server
        permission: zranks.admin
    setrank:
       usage: §2/setrank <PLAYER> <RANK>
       aliases: sr
       description: Sets the rank of a player.
       permission: zranks.setrank
    who:
       usage: §2/who
       aliases: w
       description: Displays all online players.
       permission: zranks.who
    staff:
       usage: §2/staff
       description: Displays all online staff members.
       permission: zranks.staff
    promote:
       usage: §2/promote <PLAYER>
       aliases: pr
       description: Promotes <PLAYER> to the next rank.
       permission: zranks.promote
    demote:
       usage: §2/demote <PLAYER>
       aliases: dem
       description: Demotes <PLAYER> to the previous rank.
       permission: zranks.demote